# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jekyll Theme
description: Jekyll Theme Template
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics:

collections:
  tutorials:
    output: true
  tags:
    output: true
  categories:
    output: true
  flters:
    output: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      flter-collections:
        - tags
        - categories
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "tutorials" # previously `post` in Jekyll 2.2.
    values:
      layout: "collection"
      flter-collections:
        - flters
        - tags
        - categories
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "tags" # previously `post` in Jekyll 2.2.
    values:
      layout: "flter"
      flter-attribute: tags
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "categories" # previously `post` in Jekyll 2.2.
    values:
      layout: "flter"
      flter-attribute: categories
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "flters" # previously `post` in Jekyll 2.2.
    values:
      layout: "flter"
      flter-attribute: tags
      sort-by: lesson

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
